name: 3.9 6.0 Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Caching
        uses: actions/cache@v1.2.0
        with:
          path: |
            eggs
          key: cache-Py3.9-Plone6.0
      - name: Install venv
        run: |
          pip install virtualenv
          virtualenv -p 3 .
          bin/pip install -r requirements.txt
          bin/buildout -c test-6.x.cfg install copy_ckeditor_code ckeditor pytest
      - name: Run unit tests
        run: |
          bin/pytest
      # - name: Install Firefox
      #   uses: browser-actions/setup-firefox@latest
      # - name: Install Geckodriver
      #   uses: browser-actions/setup-geckodriver@latest
      # - name: Run robot tests
      #   run: |
      #     ROBOT_BROWSER=headlessFirefox bin/pytest -k "robot and not image2"
      #     ROBOT_BROWSER=headlessFirefox bin/pytest -k "robot and image2"
      # - name: Run upgrade tests
      #   run: |
      #     bin/pytest -k "upgrade"
