name: 2.7 5.2 Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 2.7
      - name: Caching
        uses: actions/cache@v3.2.3
        with:
          path: |
            eggs
          key: cache-Py2.7-Plone5.2
      - name: Install venv
        run: |
          pip install virtualenv
          virtualenv -p 2 .
          bin/pip install -r requirements-27.txt
          bin/buildout -c test-5.2.x.cfg install copy_ckeditor_code ckeditor pytest
      - name: Run unit tests
        run: |
          bin/pytest
      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "109.0"
      - name: Install Geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.32.0"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run robot tests
        run: |
          ROBOT_BROWSER=headlessFirefox bin/pytest -k "robot and not image2"
          ROBOT_BROWSER=headlessFirefox bin/pytest -k "robot and image2"
      - name: Run upgrade tests
        run: |
          bin/pytest -k "upgrade" -s
